server:
  port: 8761
  address: 0.0.0.0

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}  # EUREKA_HOST 환경변수가 없으면 기본값 localhost 사용
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/